# Use a specific version of Node.js
FROM node:20-alpine3.20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application's source code
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Command to run the app
CMD ["npx", "vite", "--host"]
